"""Add jira_account_id

Revision ID: 727856fdc3c2
Revises: 
Create Date: 2025-04-04 22:10:42.990162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727856fdc3c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_entry')
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jira_account_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('jira_account_id')

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))

    op.create_table('time_entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('hours_worked', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
